#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Remote_hotel_customer.Resource", IsApplication=true)]

namespace Remote_hotel_customer
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int ic_menu_preferences = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int icon = 2130837505;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070005
			public const int addPasswordTextInfo = 2131165189;
			
			// aapt resource value: 0x7f07000b
			public const int backButton = 2131165195;
			
			// aapt resource value: 0x7f07000a
			public const int createReservationButton = 2131165194;
			
			// aapt resource value: 0x7f070007
			public const int dateFrom = 2131165191;
			
			// aapt resource value: 0x7f070008
			public const int dateTo = 2131165192;
			
			// aapt resource value: 0x7f070018
			public const int enterPasswordButton = 2131165208;
			
			// aapt resource value: 0x7f070011
			public const int goToEnterPasswordActivityButton = 2131165201;
			
			// aapt resource value: 0x7f07000c
			public const int goTocreateReservationButton = 2131165196;
			
			// aapt resource value: 0x7f07000e
			public const int headerDateFrom = 2131165198;
			
			// aapt resource value: 0x7f07000f
			public const int headerDateTo = 2131165199;
			
			// aapt resource value: 0x7f07000d
			public const int headerRoomNumber = 2131165197;
			
			// aapt resource value: 0x7f070017
			public const int loginButton = 2131165207;
			
			// aapt resource value: 0x7f070019
			public const int menu_settings = 2131165209;
			
			// aapt resource value: 0x7f070016
			public const int password = 2131165206;
			
			// aapt resource value: 0x7f070000
			public const int passwordEditLetter1 = 2131165184;
			
			// aapt resource value: 0x7f070001
			public const int passwordEditLetter2 = 2131165185;
			
			// aapt resource value: 0x7f070002
			public const int passwordEditLetter3 = 2131165186;
			
			// aapt resource value: 0x7f070003
			public const int passwordEditLetter4 = 2131165187;
			
			// aapt resource value: 0x7f070013
			public const int reservationDateFrom = 2131165203;
			
			// aapt resource value: 0x7f070014
			public const int reservationDateTo = 2131165204;
			
			// aapt resource value: 0x7f070010
			public const int reservationList = 2131165200;
			
			// aapt resource value: 0x7f070012
			public const int reservationRoomNumber = 2131165202;
			
			// aapt resource value: 0x7f070009
			public const int roomNumber = 2131165193;
			
			// aapt resource value: 0x7f070004
			public const int setPasswordButton = 2131165188;
			
			// aapt resource value: 0x7f070006
			public const int textView2 = 2131165190;
			
			// aapt resource value: 0x7f070015
			public const int username = 2131165205;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f040000
			public const int activity_main = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int create_reservation_view = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int dashboard = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int reservation_item_view = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int start_page = 2130968580;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f060000
			public const int Options = 2131099648;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7f030000
			public const int ic_launcher = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int ic_launcher_foreground = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int ic_launcher_round = 2130903042;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050000
			public const int app_name = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int info = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int menu_settings = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int passwordEditText = 2131034115;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
